### ISSUE TITLE
pm2 script is broken

### ISSUE THREAD

**Issue by mikeybinns** [remix-run/starter-express#15]
I cloned a new version of the starter-express, but when I go to run `npm run dev` I get the following error:
```
> remix-starter-express@1.0.0 dev C:\Users\mikey\Websites\express_tester
> pm2-dev pm2.config.js

[
  Error: Script not found: C:\Users\mikey\Websites\express_tester\remix run
      at Object.Common.resolveAppAttributes (C:\Users\mikey\Websites\express_tester\node_modules\pm2\lib\Common.js:644:11)
      at C:\Users\mikey\Websites\express_tester\node_modules\pm2\lib\API.js:1132:35
      at C:\Users\mikey\Websites\express_tester\node_modules\async\internal\withoutIndex.js:8:40
      at replenish (C:\Users\mikey\Websites\express_tester\node_modules\async\internal\eachOfLimit.js:81:17)
      at C:\Users\mikey\Websites\express_tester\node_modules\async\internal\eachOfLimit.js:86:9
      at eachLimit (C:\Users\mikey\Websites\express_tester\node_modules\async\eachLimit.js:47:43)
      at awaitable (C:\Users\mikey\Websites\express_tester\node_modules\async\internal\awaitify.js:13:28)
      at startApps (C:\Users\mikey\Websites\express_tester\node_modules\pm2\lib\API.js:1116:7)
      at C:\Users\mikey\Websites\express_tester\node_modules\pm2\lib\API.js:1097:16
      at wrapper (C:\Users\mikey\Websites\express_tester\node_modules\async\internal\once.js:12:16)
]
```

## Environment:
Windows 10
Node v12.21.0
npm v6.14.11
Starter express version current as of 4th March 2021.
Remix v13.0
pm2 v4.5.4

**Comment by ebelectr** [comment]
Use this in `pm2.config.js`:

```js
    {
      name: "Remix",
      script: "./node_modules/@remix-run/dev/cli.js",
      args: "run2",
      ignore_watch: ["."],
      env: {
        NODE_ENV: "development"
      }
    }
```

**Comment by mikeybinns** [comment]
Yep, I can confirm this worked!
Thanks @ebelectr 😀
